### ISSUE TITLE
Fail to load resources (script and style)

### ISSUE THREAD

**Issue by sabid** [akiyamaSM/laravel-nova-configuration#1]
This script and style **not load,** because the **dist** folder not exist.

Nova::script('laravel-nova-configuration', __DIR__.'/../dist/js/tool.js');
Nova::style('laravel-nova-configuration', __DIR__.'/../dist/css/tool.css');

![configuration](https://user-images.githubusercontent.com/3129855/46555273-faed2180-c89f-11e8-92c0-be5566730f5e.png)

![files](https://user-images.githubusercontent.com/3129855/46555389-59b29b00-c8a0-11e8-8bb4-fa540edb68d5.png)

My solution, in terminal.

```
cd vendor/inani/laravel-nova-configuration
npm install 
npm rum production
```

**Comment by authanram** [comment]
@sabid i did a pr https://github.com/akiyamaSM/laravel-nova-configuration/pull/2
hopefully! 😉

**Comment by akiyamaSM** [comment]
I forgot to build the scripts 🤦🤦
Thaanks for the PR

**Comment by authanram** [comment]
> I forgot to build the scripts 🤦🤦
> Thaanks for the PR

Even if you build em, you need to unignore /dist directory. (See #2)
