### ISSUE TITLE
Add Filed column

### ISSUE THREAD

**Issue by packytagliaferro** [akiyamaSM/laravel-nova-configuration#4]
Not really a bug but a suggested enhancement. 

I would add a `field` and `title` column to the pack so you can:

- Dynamically set what field shows up when you click to edit. If I am the dev I can set in the db that the `address` key with a value of `123 some st` is a text field. But the `logo` key is an image field so the client can upload a new image and not have to do it somewhere else and paste in the url
- display a friendly title and not the key.

**Comment by akiyamaSM** [comment]
To be honest when I thought about that package I had on my mind just where to store informations related to the apps such as tokens. yet I'm open to develop your suggestion. thanks for the feedback.
