### ISSUE TITLE
Error when clearing route cache

### ISSUE THREAD

**Issue by lesaff** [akiyamaSM/laravel-nova-configuration#5]
I just came across this error when I ran `php artisan route:clear` command.

Note: `php artisan optimize` will also trigger this error.

``` 
Unable to prepare route [nova-vendor/laravel-nova-configuration/getAllConfigurations] for serialization. Uses Closure. 
```
PHP Version: 7.3x
Laravel Version: 5.8.3
Laravel Nova Version: 2.0.0

Thx

**Comment by akiyamaSM** [comment]
I'll rewrite it in Controllers that way you would be able to cache routes.

**Comment by akiyamaSM** [comment]
Hello @lesaff Its fixed with the last commit.
Thansk!
